version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: .  # Adjusted base-directory to the project root directory
  files:
    - 'build_practice/**/*'  # Adjusted path to include the build output directory
