version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g create-react-app@latest

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: build_practice
  files:
    - '**/*'
